# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CapitainCook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#pods for captainCook

pod 'Firebase/Analytics'

#https://firebase.google.com/docs/ios/setup#available-pods
pod 'Firebase/Firestore'

pod 'FirebaseFirestoreSwift'



end
